#!/bin/sh
set -eu

terraform_bin="${TERRAFORM_BIN:-terraform}"
deployment_dir="infra/deployments/dashboard"

"$terraform_bin" -chdir="$deployment_dir" init -input=false
"$terraform_bin" -chdir="$deployment_dir" apply -auto-approve -input=false
